cmake_minimum_required(VERSION 3.18)
cmake_policy(SET CMP0091 NEW)

set(IGNORE_VAMP_PLUGIN_TESTER OFF CACHE STRING "Disables the tests with vamp plugin tester")
set(PARTIELS_EXE_HINT_PATH "/Applications" CACHE PATH "")
option(EMBEDDED_MODELS_IN_PACKAGE "Embeds the models in the package" ON)

set(CMAKE_XCODE_GENERATE_SCHEME ON)
set(CMAKE_OSX_DEPLOYMENT_TARGET "13.3" CACHE STRING "Minimum OS X deployment version")
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>" CACHE STRING "Default value for MSVC_RUNTIME_LIBRARY of targets" FORCE)
set(CMAKE_POSITION_INDEPENDENT_CODE TRUE CACHE BOOL "Default value for POSITION_INDEPENDENT_CODE of targets" FORCE)
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION TRUE CACHE BOOL "Default value for INTERPROCEDURAL_OPTIMIZATION of targets" FORCE)

### Include Vamp (IVE) ###
set(IVE_BUILD_HOST_LIBRARY OFF)
set(IVE_BUILD_PLUGIN_LIBRARY ON)
add_subdirectory(ircam-vamp-extension EXCLUDE_FROM_ALL)

### Include Whisper ###
set(BUILD_SHARED_LIBS OFF CACHE BOOL "ggml: build shared libraries" FORCE)
set(GGML_USE_METAL ON CACHE BOOL "ggml: use Metal" FORCE)
option(GGML_METAL_EMBED_LIBRARY "ggml: embed Metal library" ON)
option(GGML_LTO "ggml: use LTO" ON)
option(GGML_OPENMP "ggml: use OpenMP" OFF)
option(GGML_CCACHE "ggml: use ccache" OFF)
if(CMAKE_OSX_ARCHITECTURES STREQUAL "x86_64" AND NOT CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
   set(GGML_NATIVE OFF CACHE BOOL "ggml: optimize the build for the current system" FORCE)
endif()
option(WHISPER_CCACHE "whisper: use ccache if available" OFF)
if(APPLE)
  option(GGML_BLAS "ggml: use Accelerate framework" OFF)
endif()
set(WHISPER_STATIC ON)

add_subdirectory(whisper.cpp EXCLUDE_FROM_ALL)

if(APPLE)
  target_compile_options(ggml PRIVATE -Wno-shorten-64-to-32)
  target_compile_options(ggml-metal PRIVATE -Wno-shorten-64-to-32)
  target_compile_options(ggml-cpu PRIVATE -Wno-shorten-64-to-32)
  target_compile_options(ggml-base PRIVATE -Wno-shorten-64-to-32)
  foreach(WHISPERLIB IN ITEMS ggml ggml-metal ggml-cpu ggml-base ggml-blas ggml-metal whisper)
    if(TARGET ${WHISPERLIB})
        target_compile_options(${WHISPERLIB} PRIVATE -Wno-shorten-64-to-32)
        set_target_properties(${WHISPERLIB} PROPERTIES XCODE_ATTRIBUTE_GCC_WARN_64_TO_32_BIT_CONVERSION "NO")
    endif()
  endforeach()
elseif(UNIX)
  target_compile_options(ggml PRIVATE -Wno-unused-function -Wno-unused-parameter)
  target_compile_options(whisper PRIVATE -Wno-unused-function -Wno-unused-parameter)
elseif(MSVC)
  set_target_properties(ggml PROPERTIES MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
  set_target_properties(whisper PROPERTIES MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
  target_compile_options(ggml-base PRIVATE /wd4005)
endif()

### Project ###
project(WhisperVampPlugin VERSION 4.0.0 LANGUAGES C CXX)

### Version ###
execute_process(COMMAND git log -1 --format=%h WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR} OUTPUT_VARIABLE GIT_COMMIT_ID OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND git status --porcelain WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR} OUTPUT_VARIABLE GIT_HAS_DIFF OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT GIT_HAS_DIFF STREQUAL "")
  set(GIT_COMMIT_ID "${GIT_COMMIT_ID}-head")
endif()

if(NOT WVP_BUILD_TAG OR WVP_BUILD_TAG STREQUAL "")
  set(WVP_BUILD_TAG ${CMAKE_PROJECT_VERSION})
endif()
message(STATUS "Whisper Vamp Plugin: " ${WVP_BUILD_TAG} " (" ${GIT_COMMIT_ID} ")")
file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/version.txt ${WVP_BUILD_TAG})

### Package ###
set(VPP_NAME "Whisper" CACHE PATH "The name of the project" FORCE)
set(VPP_COMPANY "Ircam" CACHE PATH "The name of the company" FORCE)
set(VPP_URL "www.ircam.fr" CACHE PATH "The URL of the project")
set(VPP_APPID "f19f1fac-b588-4615-80cf-356ec2b917c1" CACHE PATH "The unique ID of the project")
set(VPP_BUILD_TAG "${WVP_BUILD_TAG}" CACHE STRING "The current tag of the project" FORCE)
set(VPP_ABOUT_FILE "${CMAKE_CURRENT_SOURCE_DIR}/resource/About.txt" CACHE PATH "The about file to add to the distribution" FORCE)
set(VPP_CHANGELOG_FILE "${CMAKE_CURRENT_SOURCE_DIR}/resource/ChangeLog.txt" CACHE PATH "The changelog file to add to the distribution" FORCE)
set(VPP_ICON_FILE "${CMAKE_CURRENT_SOURCE_DIR}/resource/Ircam-logo-noir-RS.png" CACHE PATH "The icon file to add to the distribution" FORCE)
set(VPP_DIR ${CMAKE_CURRENT_SOURCE_DIR}/package CACHE PATH "The directory of the package" FORCE)
include(vamp-plugin-packager/vamp-plugin-packager.cmake)

### Source ###
if(EMBEDDED_MODELS_IN_PACKAGE)
  file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/models")
  foreach(WVP_MODEL_CAPACITY IN ITEMS "tiny-q5_1" "small-q5_1" "medium-q5_0" "large-v2-q5_0")
    set(WVP_MODEL_PATH "${CMAKE_CURRENT_BINARY_DIR}/models/ggml-${WVP_MODEL_CAPACITY}.bin")
    if(NOT EXISTS ${WVP_MODEL_PATH})
      message(STATUS "Downloading model ggml-${WVP_MODEL_CAPACITY}.bin")
      if(WIN32)
        execute_process(COMMAND ${CMAKE_CURRENT_SOURCE_DIR}/whisper.cpp/models/download-ggml-model.cmd ${WVP_MODEL_CAPACITY})
      else()
        execute_process(COMMAND ${CMAKE_CURRENT_SOURCE_DIR}/whisper.cpp/models/download-ggml-model.sh ${WVP_MODEL_CAPACITY})
      endif()
      file(COPY_FILE "${CMAKE_CURRENT_SOURCE_DIR}/whisper.cpp/models/ggml-${WVP_MODEL_CAPACITY}.bin" ${WVP_MODEL_PATH})
      file(REMOVE "${CMAKE_CURRENT_SOURCE_DIR}/whisper.cpp/models/ggml-${WVP_MODEL_CAPACITY}.bin")
    endif()
    if(APPLE)
      vpp_add_file(${WVP_MODEL_PATH} "/Library/Application Support/Ircam/whispermodels")
    elseif(WIN32)
      vpp_add_file(${WVP_MODEL_PATH} "{commonappdata}\\Ircam\\whispermodels")
    elseif(UNIX)
      vpp_add_file(${WVP_MODEL_PATH} "$HOME/.config/Ircam/whispermodels")
    endif()
  endforeach()
endif()

set(WVP_MODEL_CPP ${CMAKE_CURRENT_BINARY_DIR}/source/wvp_model.cpp)
set(WVP_MODEL_H ${CMAKE_CURRENT_SOURCE_DIR}/source/wvp_model.h)
if(NOT EXISTS ${WVP_MODEL_CPP})
  if(WIN32)
    execute_process(COMMAND ${CMAKE_CURRENT_SOURCE_DIR}/whisper.cpp/models/download-ggml-model.cmd base-q5_1)
  else()
    execute_process(COMMAND ${CMAKE_CURRENT_SOURCE_DIR}/whisper.cpp/models/download-ggml-model.sh base-q5_1)
  endif()
  set(WVP_MODEL_PATH "${CMAKE_CURRENT_SOURCE_DIR}/whisper.cpp/models/ggml-base-q5_1.bin")
  file(RELATIVE_PATH  WVP_MODEL_HREL "${CMAKE_CURRENT_BINARY_DIR}/source" ${WVP_MODEL_H})
  file(WRITE ${WVP_MODEL_CPP} "#include \"${WVP_MODEL_HREL}\"\n\n")

  if(EXISTS ${WVP_MODEL_PATH})
    message(STATUS "Generating default model ${WVP_MODEL_PATH}")
    file(READ ${WVP_MODEL_PATH} WVP_HEX_DATA HEX)
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," WVP_HEX_DATA ${WVP_HEX_DATA})
    file(APPEND ${WVP_MODEL_CPP} "namespace Wvp\n{\n")
    file(APPEND ${WVP_MODEL_CPP} "static const unsigned char binary_data[] =\n{\n")
    file(APPEND ${WVP_MODEL_CPP} "${WVP_HEX_DATA}")
    file(APPEND ${WVP_MODEL_CPP} "};\n}\n\n")
    file(APPEND ${WVP_MODEL_CPP} "const void* Wvp::model = (const void*)Wvp::binary_data;\n")
    file(APPEND ${WVP_MODEL_CPP} "const size_t Wvp::model_size = sizeof(Wvp::binary_data);\n")
  else()
    message(WARNING "Default model ${WVP_MODEL_PATH} invalid")
    file(APPEND ${WVP_MODEL_CPP} "const void* Wvp::model = nullptr;\n")
    file(APPEND ${WVP_MODEL_CPP} "const size_t Wvp::model_size = 0;\n")
  endif()
    file(APPEND ${WVP_MODEL_CPP} "\n")
endif()

file(GLOB WVP_SOURCES
  ${CMAKE_CURRENT_SOURCE_DIR}/source/wvp.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/source/wvp.h
  ${WVP_MODEL_H}
)
source_group("sources" FILES ${WVP_SOURCES})

### Target ###
add_library(wvp SHARED ${WVP_SOURCES} ${WVP_MODEL_CPP})
ive_prepare_plugin_target(wvp)
target_link_libraries(wvp PRIVATE whisper)
target_compile_definitions(wvp PRIVATE WVP_PLUGIN_VERSION=${PROJECT_VERSION_MAJOR})

set_target_properties(wvp PROPERTIES LIBRARY_OUTPUT_NAME ircamwhisper)
vpp_add_plugin(wvp ${CMAKE_CURRENT_SOURCE_DIR}/resource/ircamwhisper.cat)

vpp_set_plugin_debug(wvp "${CMAKE_CURRENT_SOURCE_DIR}/test/whisper.ptldoc")
if(PARTIELS_EXE)
  set_target_properties(wvp PROPERTIES XCODE_SCHEME_ENVIRONMENT "VAMP_PATH=${CMAKE_CURRENT_BINARY_DIR}/Debug;WHISPERMODELPATH=/Users/guillot/Gitlab/IVP/whisper-vamp-plugin/whisper.cpp/models/ggml-base.bin")
endif()

vpp_set_plugin_install(wvp)
vpp_create_clang_format_targets(wvp ${WVP_SOURCES})

enable_testing()
vpp_enable_vamp_plugin_tester()

### Manual ###
set(WVP_MANUAL_DIR ${CMAKE_CURRENT_BINARY_DIR}/Manual)
file(MAKE_DIRECTORY ${WVP_MANUAL_DIR})

file(READ ${CMAKE_CURRENT_SOURCE_DIR}/docs/whisper-manual.md MANUAL_CONTENT)
string(REPLACE "APPVERSION" "${WVP_BUILD_TAG} (${GIT_COMMIT_ID})" MANUAL_CONTENT ${MANUAL_CONTENT})
string(REPLACE "src=\"../resource/" "src=\"${CMAKE_CURRENT_SOURCE_DIR}/resource/" MANUAL_CONTENT ${MANUAL_CONTENT})
file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/whisper-manual.md ${MANUAL_CONTENT})

file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/whisper.cpp/models/download-ggml-model.cmd DESTINATION ${WVP_MANUAL_DIR})
file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/whisper.cpp/models/download-ggml-model.sh DESTINATION ${WVP_MANUAL_DIR})
find_program(MDPDF_EXE "mdpdf")
if(MDPDF_EXE)
  add_custom_target(wvp_manual COMMAND ${MDPDF_EXE} ${CMAKE_CURRENT_BINARY_DIR}/whisper-manual.md ${WVP_MANUAL_DIR}/whisper-manual.pdf VERBATIM)
else()
  message(STATUS "Manual target cannot be generated because mdpdf is not found")
endif()

### Publishing ###
set(PROJECT_URL "https://github.com/Ircam-Partiels/whisper-vamp-plugin")
file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/whisper-release.md "## Downloads\n")
file(APPEND ${CMAKE_CURRENT_BINARY_DIR}/whisper-release.md "- [Whisper-Linux.tar.gz](${PROJECT_URL}/releases/download/${WVP_BUILD_TAG}/Whisper-Linux.tar.gz)\n")
file(APPEND ${CMAKE_CURRENT_BINARY_DIR}/whisper-release.md "- [Whisper-MacOS.pkg](${PROJECT_URL}/releases/download/${WVP_BUILD_TAG}/Whisper-MacOS.pkg)\n")
file(APPEND ${CMAKE_CURRENT_BINARY_DIR}/whisper-release.md "- [Whisper-Windows.exe](${PROJECT_URL}/releases/download/${WVP_BUILD_TAG}/Whisper-Windows.exe)\n")
file(APPEND ${CMAKE_CURRENT_BINARY_DIR}/whisper-release.md "- [Whisper-Manual.zip](${PROJECT_URL}/releases/download/${WVP_BUILD_TAG}/Whisper-Manual.zip)\n") 
